Repository Capstone-SS-2020-PDX/Covid-19-MutualAid, pull requests merged in 2020-08, with the labels that each got.

#250 Erik minor fixes
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileEditScreen.js
Labels: enhancement, front end

#264 Added front-end elements for flagging a post
  react-native/components/PostingList.js
  react-native/components/PostingListItem.js
  react-native/package.json
  react-native/screens/PostingDetailScreen.js
Labels: enhancement, front end

#265 Erik extract map component
  react-native/components/Map.js
  react-native/config/colors.js
  react-native/screens/PostingDetailScreen.js
Labels: front end, refactor

#259 Gcp secrets
  Makefile
  django/Dockerfile
  django/app.yaml
  django/cgproj/settings.py
Labels: Automation, back end, security

#269 User agreements screen before register
  react-native/components/CustomModal.js
  react-native/navigation/AuthStack.js
  react-native/package.json
  react-native/screens/LoginScreen.js
  react-native/screens/RegisterScreen.js
  react-native/screens/UserAgreementScreen.js
Labels: front end

#221 Login / register fail modal in AuthProvider
  react-native/components/CustomModal.js
  react-native/providers/AuthProvider.js
  react-native/screens/LoginScreen.js
Labels: front end

#270 Add favorite icon to posting list
  react-native/components/CustomModal.js
  react-native/components/PostingList.js
  react-native/components/PostingListItem.js
  react-native/screens/PostingDetailScreen.js
Labels: UI/UX, enhancement, front end

#271 Erik add postings to context
  react-native/components/CustomModal.js
  react-native/components/DrawerContent.js
  react-native/components/Map.js
  react-native/components/PostingList.js
  react-native/config/navigation-options.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/ProfileCreationStack.js
  react-native/navigation/ProfileStack.js
  react-native/navigation/SettingsStack.js
  react-native/package.json
  react-native/providers/AuthProvider.js
  react-native/screens/EditPostingScreen.js
  react-native/screens/FlaggedPostingsScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/PostingListScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileScreen.js
  react-native/screens/SavedPostingListScreen.js
  react-native/screens/SettingsScreen.js
  react-native/screens/UserPostingListScreen.js
Labels: enhancement, front end, refactor

#260 Add radius filter
  django/cgapi/filters.py
  django/cgapi/views.py
  django/cgproj/settings.py
  django/requirements.txt
Labels: back end, enhancement

#273 Erik Fix Map
  react-native/components/Map.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/ProfileScreen.js
Labels: bug, front end, refactor

#275 Some Bug Fixes
  react-native/components/Map.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
Labels: bug, front end
