Repository Capstone-SS-2020-PDX/Covid-19-MutualAid, pull requests merged in 2020-07, with the labels that each got.

#126 Change make js to default target
  Makefile
Labels: Automation, enhancement

#151 Erik generify options
  react-native/config/headerOptions.js
  react-native/config/navigation-options.js
  react-native/navigation/AboutStack.js
  react-native/navigation/HomeStack.js
  react-native/navigation/PostingCreationStack.js
  react-native/navigation/SearchStack.js
  react-native/navigation/addPostingsRoutes.js
Labels: front end, refactor

#147 Improve Responsiveness on DetailScreen
  react-native/navigation/addPostingsRoutes.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
Labels: UI/UX, front end

#152 Add toast notification for success or failure
  react-native/package.json
  react-native/screens/PostingCreationScreen.js
Labels: bug, enhancement, front end

#157 Erik email modal
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
Labels: enhancement, front end

#158 Use responsive fonts for #156
  react-native/assets/splash.png
  react-native/package.json
  react-native/screens/PostingDetailScreen.js
Labels: front end

#173 Cleanup repo a bit
  README.md
  pre-push.sh
  qa/suite.postman_collection.json
Labels: documentation

#172 Input always visible (including iOS)
  react-native/screens/LoginScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/RegisterScreen.js
Labels: UI/UX, front end

#187 Slightly revise issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#188 Posting Creation Screen image resets now!
  react-native/components/CustomImagePicker.js
  react-native/screens/PostingCreationScreen.js
Labels: UI/UX

#205 Integrate Home Communities and Profile Editing
  react-native/components/CustomImagePicker.js
  react-native/components/CustomModal.js
  react-native/components/CustomToast.js
  react-native/components/PostingList.js
  react-native/components/PostingListItem.js
  react-native/config/navigation-options.js
  react-native/config/urls.js
  react-native/navigation/HomeStack.js
  react-native/navigation/ProfileStack.js
  react-native/providers/AuthProvider.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileEditScreen.js
  react-native/screens/ProfileScreen.js
  react-native/screens/RegisterScreen.js
Labels: enhancement, front end

#203 App engine flex deployed
  django/Dockerfile
  django/app.yaml
  django/cgapi/models.py
  django/cgproj/settings.py
  django/requirements.txt
Labels: back end

#208 Erik - next/done buttons on forms
  react-native/screens/LoginScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/ProfileEditScreen.js
  react-native/screens/RegisterScreen.js
Labels: bug, enhancement, front end

#215 Erik fix update profile edit bug
  react-native/screens/ProfileEditScreen.js
Labels: bug, front end

#216 Erik edit postings
  react-native/components/CustomModal.js
  react-native/navigation/UserPostingStack.js
  react-native/navigation/addPostingsRoutes.js
  react-native/screens/EditPostingScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/ProfileEditScreen.js
Labels: enhancement, front end

#220 Erik fix ios crash on Login
  react-native/components/CustomModal.js
  react-native/navigation/HomeStack.js
  react-native/providers/AuthProvider.js
  react-native/screens/LoginScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/RegisterScreen.js
Labels: bug

#224 Erik add communities list
  react-native/components/CommunityList.js
  react-native/components/CommunityListItem.js
  react-native/components/DrawerContent.js
  react-native/components/JoinCommunitiesList.js
  react-native/components/JoinCommunitiesListItem.js
  react-native/navigation/CommunityStack.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/HomeStack.js
  react-native/screens/CommunityListScreen.js
  react-native/screens/EditPostingScreen.js
  react-native/screens/JoinCommunitiesScreen.js
  react-native/screens/PostingListScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileEditScreen.js
  react-native/utility/helperFunctions.js
Labels: enhancement, front end

#222 Improve post creation fields
  react-native/package.json
  react-native/screens/PostingCreationScreen.js
Labels: enhancement, front end

#230 Erik add favorites
  react-native/components/DrawerContent.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/SavedPostingStack.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/SavedPostingListScreen.js
Labels: enhancement, front end

#228 Geolocation frontend and backend
  django/app.yaml
  django/cgapi/migrations/0009_posting_changes.py
  django/cgapi/migrations/0010_posting_point.py
  django/cgapi/migrations/0011_locations_added.py
  django/cgapi/migrations/0012_rename_home.py
  django/cgapi/models.py
  django/cgapi/serializers.py
  react-native/config/urls.js
  react-native/package.json
  react-native/screens/PostingCreationScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileScreen.js
  react-native/screens/RegisterScreen.js
Labels: back end, enhancement, front end

#239 Erik enable profile deletion
  react-native/package.json
  react-native/screens/PostingCreationScreen.js
  react-native/screens/ProfileEditScreen.js
  react-native/screens/ProfileScreen.js
Labels: enhancement, front end

#240 Form validation
  react-native/components/CustomImagePicker.js
  react-native/components/CustomModal.js
  react-native/config/urls.js
  react-native/package.json
  react-native/providers/AuthProvider.js
  react-native/screens/EditPostingScreen.js
  react-native/screens/LoginScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileEditScreen.js
  react-native/screens/ProfileScreen.js
  react-native/screens/RegisterScreen.js
Labels: enhancement, front end

#248 Erik use new picker
  react-native/components/CommunityPicker.js
  react-native/components/DrawerContent.js
  react-native/navigation/NavTabs.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/ProfileCreationScreen.js
  react-native/screens/ProfileEditScreen.js
Labels: UI/UX, enhancement, front end

#251 Fix email ssl
  django/Dockerfile
  django/cgproj/settings.py
Labels: back end, bug

#253 Erik add admin ui
  react-native/components/CommunityList.js
  react-native/components/DrawerContent.js
  react-native/components/PostingList.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/ModeratorStack.js
  react-native/providers/AuthProvider.js
  react-native/screens/FlaggedPostingsScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
Labels: enhancement, front end
