Repository Capstone-SS-2020-PDX/Covid-19-MutualAid, pull requests merged in 2020-05, with the labels that each got.

#23 Add git prepush hook for pytest and jest
  .gitignore
  README.md
  django/pytest.ini
  django/tests/tests.py
  django/todoapi/migrations/0003_auto_20200508_2113.py
  django/todoapi/models.py
  django/todoapi/serializers.py
  django/todoapi/views.py
  django/todoproj/urls.py
  docker-compose.yaml
  pre-push.sh
  react-native/package.json
  react-native/tests/math.test.js
Labels: enhancement

#40 Add yarn.lock with initial react-native libs
  react-native/yarn.lock
Labels: front end

#60 Sorry :(
  django/todoapi/models.py
  django/todoapi/serializers.py
Labels: back end

#61 Remove extra python files
  models.py
  serializers.py
Labels: back end, bug

#64 Django file names
  django/cgapi/__init__.py
  django/cgapi/admin.py
  django/cgapi/apps.py
  django/cgapi/migrations/0001_squashed.py
  django/cgapi/migrations/__init__.py
  django/cgapi/models.py
  django/cgapi/serializers.py
  django/cgapi/tests.py
  django/cgapi/views.py
  django/cgproj/__init__.py
  django/cgproj/asgi.py
  django/cgproj/settings.py
  django/cgproj/urls.py
  django/cgproj/wsgi.py
  django/main.py
  django/manage.py
  django/pytest.ini
  django/todoapi/apps.py
  pre-push.sh
  qa/suite.postman_collection.json
  react-native/App.js
Labels: Automation, enhancement

#65 Rename screens dir to components, change refs
  react-native/App.js
  react-native/components/PostingCreationScreen.js
  react-native/components/PostingListScreen.js
Labels: enhancement, front end

#76 Sean modularize posting screens
  react-native/App.js
  react-native/components/PostingCreationScreen.js
  react-native/components/PostingListScreen.js
  react-native/package.json
  react-native/yarn.lock
Labels: enhancement, front end
