Repository Capstone-SS-2020-PDX/Covid-19-MutualAid, pull requests merged in 2020-06, with the labels that each got.

#86 Fix the warning on Posting List Screen
  react-native/components/PostingListScreen.js
Labels: bug, front end

#83 Automate backend deploy - Let's just use a script
  .gitignore
  Makefile
  django/cgproj/settings.py
  django/cloudbuild.yaml
Labels: Automation, back end

#90 Upgrade yarn package for security
  react-native/package.json
  react-native/yarn.lock
Labels: front end, security

#93 Erik rn baseline
  react-native/App.js
  react-native/assets/CommonGoods-Logo.png
  react-native/assets/CommonGoods-Title.png
  react-native/assets/fonts/OpenSans-Bold.ttf
  react-native/assets/fonts/OpenSans-Regular.ttf
  react-native/components/Card.js
  react-native/components/Center.js
  react-native/components/CustomButton.js
  react-native/components/CustomText.js
  react-native/components/PostingCreationScreen.js
  react-native/components/PostingList.js
  react-native/components/PostingListItem.js
  react-native/config/dimensions.js
  react-native/config/headerOptions.js
  react-native/hooks/useInputState.js
  react-native/navigation/AboutStack.js
  react-native/navigation/AuthStack.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/HomeStack.js
  react-native/navigation/NavTabs.js
  react-native/navigation/PostingCreationStack.js
  react-native/navigation/Routes.js
  react-native/navigation/SearchStack.js
  react-native/navigation/addPostingsRoutes.js
  react-native/package.json
  react-native/providers/AuthProvider.js
  react-native/screens/AboutScreen.js
  react-native/screens/EditPostingScreen.js
  react-native/screens/FeedScreen.js
  react-native/screens/HomeScreen.js
  react-native/screens/LoginScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
  react-native/screens/PostingListScreen.js
  react-native/screens/RegisterScreen.js
  react-native/screens/SearchScreen.js
  react-native/web-build/register-service-worker.js
  react-native/yarn.lock
Labels: enhancement, front end

#106 Get post creation screen talking to API
  react-native/screens/PostingCreationScreen.js
Labels: back end, enhancement, front end

#109 Erik update drawer
  react-native/components/DrawerContent.js
  react-native/navigation/DrawerNav.js
  react-native/navigation/HomeStack.js
  react-native/navigation/PostingCreationStack.js
  react-native/navigation/SearchStack.js
  react-native/package.json
  react-native/screens/FeedScreen.js
  react-native/screens/PostingCreationScreen.js
Labels: UI/UX, enhancement, front end

#114 Prereq 2 fix - No Yarn
  qa/prereq-linux2.sh
Labels: Automation

#123 Erik update textinputs
  react-native/config/colors.js
  react-native/screens/FeedScreen.js
  react-native/screens/LoginScreen.js
  react-native/screens/RegisterScreen.js
Labels: UI/UX, enhancement, front end

#127 Erik Project Enhancement
  react-native/components/PostingList.js
  react-native/components/PostingListItem.js
  react-native/navigation/addPostingsRoutes.js
  react-native/screens/FeedScreen.js
  react-native/screens/PostingCreationScreen.js
  react-native/screens/PostingDetailScreen.js
Labels: enhancement, front end
